---
  - name: Detect base image capabilities
    shell: test -e /usr/local/bin/docker-php-source
    ignore_errors: true
    register: docker_php_image

  - include: "{{ item }}"
    with_first_found:
      - files:
          - "tasks_dependencies_{{ ansible_distribution | lower }}_{{ ansible_distribution_release | lower }}_install.yml"
        skip: true
    when: docker_php_image and option_auto_dependencies

  - include: tasks_php_dockerofficial.yml
    when: docker_php_image

  - include: tasks_php_alpine.yml
    when: docker_php_image | failed and ( ansible_distribution == "Alpine" )

  - include: tasks_composer.yml
    when: option_install_composer

  - include: "{{ item }}"
    with_first_found:
      - files:
          - "tasks_dependencies_{{ ansible_distribution | lower }}_{{ ansible_distribution_release | lower }}_remove.yml"
        skip: true
    when: docker_php_image and option_auto_dependencies
